# -*- coding: utf-8 -*-
"""HANDLING_Time_Date.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaaGTy1Kzb4P3zsGZsDO_YM_U25TUjId
"""

import pandas as pd
import numpy as np

date=pd.read_csv('/content/orders.csv')

time=pd.read_csv('/content/messages.csv')

date.head()

time.head()

date.info()

time.info()

# converting to datatime datatype
date['date']=pd.to_datetime(date['date'])

date.head()

date.info()

date['date_year']=date['date'].dt.year

date.sample(8)

date['date_month_no']=date['date'].dt.month

date.sample(7)

date['date_month_name']=date['date'].dt.month_name()

date.sample(9)

date['date_day']=date['date'].dt.day

date.head()

date['date_dow']=date['date'].dt.dayofweek

date.head()

date['date_dow_name']=date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

date['date_is_weeked']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

date['date_week']=date['date'].dt.weekday
date.drop(columns=['product_id','city_id','orders']).head()

date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()



date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.drop(columns=['product_id','city_id','orders']).head()

import datetime

today=datetime.datetime.today()
 today

today-date['date']

(today-date['date']).dt.days

# Months passed

np.round((today -date['date']) / np.timedelta64(1, 'M'),0)

time.info()

time['date']=pd.to_datetime(time['date'])

time.info()

# Converting to datetime datatype
time['date']=pd.to_datetime(time['date'])

time.info()

time['hour']=time['date'].dt.hour
time['mim']=time['date'].dt.minute
time['date']=time['date'].dt.second
time.head()

time['time'] = time['date'].dt.time

time.head()

today-time['date']

# in seconds

(today - time['date'])/np.timedelta64(1,'s')

# in minutes

(today - time['date'])/np.timedelta64(1,'m')

# in hours

(today - time['date'])/np.timedelta64(1,'h')