# -*- coding: utf-8 -*-
"""handling mixed variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u827I5W1jWRGrA79u2V0b-yjR6tJ1YPT
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/titanic.csv')

df

df.head()

df['number'].unique()

fig=df['number'].value_counts().plot.bar()
fig.set_title('Passengers travelling with')

df['number_numerical']=pd.to_numeric(df['number'],errors='coerce',downcast='integer')

df['number_catagorical']=np.where(df['number_numerical'].isnull(),df['number'],np.nan)

df.head()

df['Cabin'].unique()

df['Ticket'].unique()

df['cabin_num']=df['Cabin'].str.extract('(\d+)')
df['cabin_cat']=df['Cabin'].str[0]

df['cabin_cat'].value_counts().plot(kind='bar')

# extract the last bit of ticket as number
df['ticket_num']=df['Ticket'].apply(lambda s:s.split()[0])
df['ticket_num']=pd.to_numeric(df['ticket_num'],errors='coerce',downcast='integer')

# extract the first part of ticket as category
df['ticket_cat']=df['Ticket'].apply(lambda s:s.split()[0])
df['ticket_cat']=np.where(df['ticket_cat'].str.isdigit(),np.nan,df['ticket_cat'])

df.head()

df['ticket_cat'].unique()

