# -*- coding: utf-8 -*-
"""Write a Python program to concatenate two tuples and create a new tuple..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CfPopsOmqBEte7zLfL3nTAjYzz3AQgeL
"""

#  Write a Python program to concatenate two tuples and create a new tuple.
a=(1,2,3,4,5)
b=(4,5,6,7,8)
c=a+b
print(c)

